/**
 * Iconos profesionales (Lucide) con nombres semánticos.
 * Centralizar aquí mantiene la coherencia visual y facilita cambiarlos.
 * Nada de emojis en la interfaz: solo estos iconos de trazo.
 */
export {
  LayoutDashboard as DashboardIcon,
  ClipboardList as BriefingIcon,
  Shield as TeamIcon,
  Users as SquadIcon,
  User as PlayerIcon,
  UserCog as StaffIcon,
  Upload as ImportIcon,
  Download as DownloadIcon,
  Settings as SettingsIcon,
  LogOut as LogoutIcon,
  Goal as GoalIcon,
  SquareStack as CardsIcon,
  AlertTriangle as AlertIcon,
  ShieldAlert as RiskIcon,
  StickyNote as NoteIcon,
  Plus as PlusIcon,
  Pencil as EditIcon,
  Trash2 as DeleteIcon,
  Printer as PrintIcon,
  Image as ImageIcon,
  ArrowLeft as BackIcon,
  ArrowRight as ForwardIcon,
  ChevronRight as ChevronRightIcon,
  Calendar as CalendarIcon,
  MapPin as PinIcon,
  Flag as FlagIcon,
  Disc3 as WhistleIcon,
  CircleUserRound as RefereeIcon,
  Activity as ActivityIcon,
  TrendingUp as TrendingIcon,
  Gauge as GaugeIcon,
  Target as TargetIcon,
  Megaphone as ProtestIcon,
  Footprints as PressIcon,
  Crosshair as OffsideIcon,
  CircleDot as BallIcon,
  Square as SquareIcon,
  Check as CheckIcon,
  X as CloseIcon,
  Sparkles as KeyIcon,
  Clock as ClockIcon,
  Eye as WatchIcon,
  ListChecks as ChecklistIcon,
  PenLine as PenIcon,
  Plug as PluginIcon,
  Lock as LockIcon,
} from "lucide-react";
